"""Data-driven slip-system registry for FCC / BCC (+ user-defined).

A slip system is (b, n, t): Burgers direction b in the glide plane with
normal n, and line direction t = n x b. Tables are generated by enumerating
the sign/permutation variants of a representative plane and Burgers family
under the cubic point group, filtering to b.n == 0 (glide), deduplicating
+/-(b, n) pairs.

CUBIC ONLY in 4.3a: Miller indices are treated as Cartesian (valid for
cubic — FCC and BCC). HCP (4.3b) converts via the cell matrix first.
Spec: docs/superpowers/specs/2026-06-13-m4-stage43-slip-systems-design.md.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass
from typing import TYPE_CHECKING, cast

import numpy as np

if TYPE_CHECKING:
    from dfxm_geo.crystal.cell import UnitCell


@dataclass(frozen=True)
class SlipFamily:
    name: str
    plane_family: tuple[int, int, int]
    burgers_family: tuple[int, int, int]
    literal: bool = False  # when True: yield exactly this (b, n) pair, no symmetry expansion


@dataclass(frozen=True)
class SlipSystem:
    b: tuple[int, int, int]  # integer Burgers direction (Miller)
    n: tuple[int, int, int]  # integer plane normal (Miller)
    t: tuple[int, int, int]  # integer line direction n x b
    family: str


_REGISTRY: dict[str, tuple[SlipFamily, ...]] = {
    "fcc": (SlipFamily("{111}<110>", (1, 1, 1), (1, 1, 0)),),
    "bcc": (
        SlipFamily("{110}<111>", (1, 1, 0), (1, 1, 1)),
        SlipFamily("{112}<111>", (1, 1, 2), (1, 1, 1)),
    ),
}

# Explicit ORDERED FCC {111}<110> slip table — the hand-authored v2.x sequence
# (forward_model._SLIP_SYSTEM_111, deleted in M4 Stage 4.3a Task 8). The
# symmetry enumerator (`_enumerate_family`) sorts planes/Burgers
# lexicographically, which does NOT match this order. The ORDER is load-bearing:
# `random_dislocations` draws `rng.integers(0, 12)` into this list, so the
# sequence determines which (b, n, t) each dislocation gets, and the wall mode
# uses entry [0] as its single slip system. Returning the symmetry enumeration
# instead would silently change every FCC random/wall forward image. The set
# (b, n, t up to sign) is identical to the enumerator output — asserted in
# tests (`test_fcc_ordered_table_is_complete_111_110_family`,
# `test_fcc_registry_equals_legacy_slip_table`) and guarded at module import
# below — so nothing is dropped; only the order is pinned for bit-identity.
_FCC_111_110_ORDERED: tuple[
    tuple[tuple[int, int, int], tuple[int, int, int], tuple[int, int, int]], ...
] = (
    # Plane (1, 1, 1)
    ((1, -1, 0), (1, 1, 1), (1, 1, -2)),
    ((-1, 0, 1), (1, 1, 1), (-1, 2, -1)),
    ((0, 1, -1), (1, 1, 1), (-2, 1, 1)),
    # Plane (1, -1, 1)
    ((1, 1, 0), (1, -1, 1), (1, -1, -2)),
    ((-1, 0, 1), (1, -1, 1), (-1, -2, -1)),
    ((0, -1, -1), (1, -1, 1), (-2, -1, 1)),
    # Plane (-1, 1, 1)
    ((0, 1, -1), (-1, 1, 1), (-2, -1, -1)),
    ((1, 0, 1), (-1, 1, 1), (1, 2, -1)),
    ((1, 1, 0), (-1, 1, 1), (-1, 1, -2)),
    # Plane (1, 1, -1)
    ((0, 1, 1), (1, 1, -1), (2, -1, 1)),
    ((1, -1, 0), (1, 1, -1), (-1, -1, -2)),
    ((1, 0, 1), (1, 1, -1), (1, -2, -1)),
)


def _variants(rep: tuple[int, int, int]) -> set[tuple[int, int, int]]:
    """All distinct sign+permutation variants of a Miller family rep."""
    out: set[tuple[int, int, int]] = set()
    for perm in set(itertools.permutations(rep)):
        for signs in itertools.product((1, -1), repeat=3):
            out.add(
                cast("tuple[int, int, int]", tuple(s * c for s, c in zip(signs, perm, strict=True)))
            )
    return out


def _canon(v: tuple[int, int, int]) -> tuple[int, int, int]:
    """Canonical sign: leading nonzero positive (so v and -v collapse)."""
    for c in v:
        if c != 0:
            return v if c > 0 else tuple(-x for x in v)  # type: ignore[return-value]
    return v


def _enumerate_orbit(fam: SlipFamily) -> list[SlipSystem]:
    """Symmetry-orbit enumeration: lexicographic plane/Burgers expansion.

    The generic glide-system generator. Order is the deterministic
    ``sorted(planes) x sorted(burgers)`` sequence — fine for BCC (no legacy to
    match) but NOT the v2.x FCC order, which `_enumerate_family` overrides for
    bit-identity.
    """
    planes = {_canon(p) for p in _variants(fam.plane_family)}
    burgers = _variants(fam.burgers_family)
    seen: set[tuple[tuple[int, int, int], tuple[int, int, int]]] = set()
    systems: list[SlipSystem] = []
    for n in sorted(planes):
        for b in sorted(burgers):
            if b[0] * n[0] + b[1] * n[1] + b[2] * n[2] != 0:
                continue  # not a glide system
            key = (_canon(b), n)
            if key in seen:
                continue
            seen.add(key)
            t = cast("tuple[int, int, int]", tuple(int(x) for x in np.cross(n, b)))
            systems.append(SlipSystem(b=b, n=n, t=t, family=fam.name))
    return systems


def _enumerate_family(fam: SlipFamily) -> list[SlipSystem]:
    if fam.literal:
        # Literal families: yield exactly one system from the stored (b, n) pair,
        # with no symmetry-orbit expansion. The b.n==0 check was done at registration.
        n = fam.plane_family
        b = fam.burgers_family
        t = cast("tuple[int, int, int]", tuple(int(x) for x in np.cross(n, b)))
        return [SlipSystem(b=b, n=n, t=t, family=fam.name)]
    if (
        fam.name == "{111}<110>"
        and fam.plane_family == (1, 1, 1)
        and fam.burgers_family == (1, 1, 0)
    ):
        # FCC {111}<110>: return the explicit ORDERED table, not the lexicographic
        # symmetry enumeration, so the v2.x random/wall draw order is preserved
        # bit-for-bit (see _FCC_111_110_ORDERED). Set-completeness vs the
        # enumerator is guarded at import (the assertion below this function).
        return [SlipSystem(b=b, n=n, t=t, family=fam.name) for b, n, t in _FCC_111_110_ORDERED]
    return _enumerate_orbit(fam)


def _assert_fcc_ordered_table_complete() -> None:
    """Guard (run at import): the explicit ordered FCC table must SET-equal the
    full {111}<110> symmetry orbit, so pinning the order never drops a system."""
    orbit = _enumerate_orbit(SlipFamily("{111}<110>", (1, 1, 1), (1, 1, 0)))
    orbit_set = {(_canon(s.b), _canon(s.n)) for s in orbit}
    table_set = {(_canon(b), _canon(n)) for b, n, _t in _FCC_111_110_ORDERED}
    if orbit_set != table_set or len(_FCC_111_110_ORDERED) != len(orbit):
        raise AssertionError(  # pragma: no cover - defensive import-time guard
            "_FCC_111_110_ORDERED desynced from the {111}<110> symmetry orbit: "
            f"table has {len(_FCC_111_110_ORDERED)} systems {sorted(table_set)}, "
            f"orbit has {len(orbit)} {sorted(orbit_set)}."
        )


_assert_fcc_ordered_table_complete()


def _families_for(structure: str, families: list[str] | None) -> tuple[SlipFamily, ...]:
    if structure not in _REGISTRY:
        raise ValueError(f"unknown structure {structure!r}; expected one of {sorted(_REGISTRY)}")
    avail = _REGISTRY[structure]
    if families is None:
        return avail
    by_name = {f.name: f for f in avail}
    try:
        return tuple(by_name[name] for name in families)
    except KeyError as exc:
        raise ValueError(
            f"slip family {exc.args[0]!r} not defined for {structure!r}; "
            f"available: {sorted(by_name)}"
        ) from None


def slip_systems(structure: str, *, families: list[str] | None = None) -> list[SlipSystem]:
    """All (b, n, t) slip systems for a structure (optionally a family subset)."""
    out: list[SlipSystem] = []
    for fam in _families_for(structure, families):
        out.extend(_enumerate_family(fam))
    return out


def plane_normals(
    structure: str, *, families: list[str] | None = None
) -> list[tuple[int, int, int]]:
    """Distinct slip-plane normals (replaces _ALL_111_PLANES), canonical sign."""
    seen: list[tuple[int, int, int]] = []
    for s in slip_systems(structure, families=families):
        c = _canon(s.n)
        if c not in seen:
            seen.append(c)
    return seen


# Lattice-translation fraction per family: the slip Burgers is this fraction
# of the integer direction's lattice vector (1/2 for the centered-lattice
# translations <110>_fcc, <111>_bcc).
_BURGERS_FRACTION: dict[str, float] = {
    "{111}<110>": 0.5,
    "{110}<111>": 0.5,
    "{112}<111>": 0.5,
}


def burgers_in_plane(
    structure: str, plane: tuple[int, int, int], *, families: list[str] | None = None
) -> np.ndarray:
    """Unit Burgers directions lying in `plane` (+ negatives), shape (m, 3).

    Replaces crystal.burgers._BASIS_TABLE/burgers_vectors. Per-vector
    Euclidean normalization (bit-identical to the old /sqrt(2) for FCC <110>).
    """
    cn = _canon(plane)
    pos: list[tuple[int, int, int]] = []
    for s in slip_systems(structure, families=families):
        if _canon(s.n) == cn and _canon(s.b) not in pos:
            pos.append(_canon(s.b))
    if not pos:
        raise ValueError(
            f"{plane} is not a slip plane for structure {structure!r}; "
            f"planes: {plane_normals(structure, families=families)}"
        )
    basis = np.array(pos, dtype=float)
    unit = basis / np.linalg.norm(basis, axis=1, keepdims=True)
    return np.vstack([unit, -unit])


def derive_structure_type(
    *,
    structure_type: str | None,
    space_group: str | None,
    lattice: str | None,
) -> str:
    """Resolve the structure family.

    Precedence: when a space group is present it is authoritative (the
    crystallographic evidence overrides a possibly-wrong user assertion) —
    derive from it and raise if an explicit structure_type contradicts it.
    With no space group, explicit structure_type wins over the default; with
    neither, 'fcc' (back-compat). The `lattice` param is accepted for API
    stability (4.3b will use it for HCP cell conversion) and is currently unused.
    """
    if space_group is not None:
        from dfxm_geo.crystal.cif import space_group_structure_family

        derived = space_group_structure_family(space_group)
        if structure_type is not None and structure_type != derived:
            raise ValueError(
                f"structure_type={structure_type!r} contradicts space group "
                f"{space_group!r} (implies {derived!r})."
            )
        return derived
    if structure_type is not None:
        if structure_type not in _REGISTRY and structure_type != "hcp":
            raise ValueError(
                f"unknown structure_type {structure_type!r}; expected one of "
                f"{sorted(_REGISTRY)} (hcp lands in 4.3b)."
            )
        return structure_type
    return "fcc"


def register_custom(name: str, systems: list[dict]) -> None:
    """Register a user-defined structure from ``[[crystal.slip_system]]`` entries.

    Each entry: ``{"plane": (h, k, l), "burgers": (u, v, w)}``. Validates
    b·n == 0. Stored as literal single-system families so
    ``slip_systems(name)`` returns exactly those systems (no symmetry-orbit
    expansion).

    Args:
        name: structure key (e.g. ``"custom:Fe"``); replaces any existing entry.
        systems: list of dicts with "plane" and "burgers" keys (integer triples).

    Raises:
        ValueError: if any system has b·n != 0 (not a glide system).
    """
    fams: list[SlipFamily] = []
    for i, s in enumerate(systems):
        plane = tuple(int(x) for x in s["plane"])
        b = tuple(int(x) for x in s["burgers"])
        if b[0] * plane[0] + b[1] * plane[1] + b[2] * plane[2] != 0:
            raise ValueError(f"custom slip system {i}: b.n != 0 (b={b}, n={plane}); not glide")
        fams.append(
            SlipFamily(
                f"custom{i}",
                cast("tuple[int, int, int]", plane),
                cast("tuple[int, int, int]", b),
                literal=True,
            )
        )
    new = tuple(fams)
    if name in _REGISTRY and _REGISTRY[name] != new:
        import warnings

        warnings.warn(
            f"register_custom: replacing existing registry entry {name!r} with "
            "different slip systems; if two configs share the same 'material' key "
            "this may be unintentional.",
            stacklevel=2,
        )
    _REGISTRY[name] = new


def burgers_magnitude(structure: str, family: str, cell: UnitCell) -> float:
    """Burgers magnitude |b| in micrometres for a structure's family, from the cell.

    |b| = fraction * |A . b_int|, A in metres -> result in um. Cubic FCC
    1/2<110> -> a/sqrt(2); BCC 1/2<111> -> a*sqrt(3)/2.
    """
    if structure not in _REGISTRY:
        raise ValueError(f"unknown structure {structure!r}; expected one of {sorted(_REGISTRY)}")
    matches = [f for f in _REGISTRY[structure] if f.name == family]
    if not matches:
        raise ValueError(
            f"slip family {family!r} not defined for {structure!r}; "
            f"available: {sorted(f.name for f in _REGISTRY[structure])}"
        )
    if family not in _BURGERS_FRACTION:
        raise ValueError(
            f"no lattice-translation fraction registered for family {family!r}; "
            f"add it to _BURGERS_FRACTION."
        )
    b_int = np.array(matches[0].burgers_family, dtype=float)
    cart = cell.A @ b_int  # metres
    return float(_BURGERS_FRACTION[family] * np.linalg.norm(cart) * 1e6)
