"""Data-driven slip-system registry for cubic (FCC/BCC) + HCP (hexagonal enumerator).

A slip system is (b, n, t): Burgers direction b in the glide plane with
normal n, and line direction t = n x b. Tables are generated by enumerating
the sign/permutation variants of a representative plane and Burgers family
under the relevant point group, filtering to b.n == 0 (glide), deduplicating
+/-(b, n) pairs.

Cubic (FCC/BCC): Miller indices are treated as Cartesian (valid for cubic).
HCP: hexagonal enumerator works in 4-index Miller–Bravais notation; 3-index
conversion via hkil_to_hkl (plane) and uvtw_to_uvw (direction). The cell
matrix A/B is applied at geometry-build time (Tasks 4/5+), not here.
Spec: docs/superpowers/specs/2026-06-13-m4-stage43-slip-systems-design.md.
"""

from __future__ import annotations

import itertools
import math
from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal, cast

import numpy as np

if TYPE_CHECKING:
    from dfxm_geo.crystal.cell import UnitCell


def _reduce(v: tuple[int, ...]) -> tuple[int, ...]:
    """Divide an integer index vector by the gcd of its components (sign kept)."""
    g = 0
    for c in v:
        g = math.gcd(g, abs(int(c)))
    if g == 0:
        return tuple(int(c) for c in v)
    return tuple(int(c) // g for c in v)


def hkil_to_hkl(hkil: tuple[int, int, int, int]) -> tuple[int, int, int]:
    """4-index Miller–Bravais PLANE (h k i l), i = -(h+k), -> reduced 3-index (h k l)."""
    h, k, i, l = (int(x) for x in hkil)
    if i != -(h + k):
        raise ValueError(f"Miller–Bravais plane {hkil}: i must equal -(h+k) = {-(h + k)}.")
    return cast("tuple[int, int, int]", _reduce((h, k, l)))


def uvtw_to_uvw(uvtw: tuple[int, int, int, int]) -> tuple[int, int, int]:
    """4-index DIRECTION [u v t w], t = -(u+v), -> reduced 3-index [U V W].

    U = 2u + v, V = u + 2v, W = w, then divide by gcd. (Weber symbols.)
    """
    u, v, t, w = (int(x) for x in uvtw)
    if t != -(u + v):
        raise ValueError(f"Miller–Bravais direction {uvtw}: t must equal -(u+v) = {-(u + v)}.")
    return cast("tuple[int, int, int]", _reduce((2 * u + v, u + 2 * v, w)))


@dataclass(frozen=True)
class SlipFamily:
    name: str
    plane_family: tuple[int, ...]  # 3-index (cubic) or 4-index (hcp) representative
    burgers_family: tuple[int, ...]
    literal: bool = False  # when True: yield exactly this (b, n) pair, no symmetry expansion
    enumerator: Literal["cubic", "hex"] = "cubic"  # "cubic" (sign+perm) | "hex" (Miller–Bravais)


@dataclass(frozen=True)
class SlipSystem:
    b: tuple[int, int, int]  # integer Burgers direction (Miller)
    n: tuple[int, int, int]  # integer plane normal (Miller)
    t: tuple[int, int, int]  # integer line direction n x b
    family: str


_REGISTRY: dict[str, tuple[SlipFamily, ...]] = {
    "fcc": (SlipFamily("{111}<110>", (1, 1, 1), (1, 1, 0)),),
    "bcc": (
        SlipFamily("{110}<111>", (1, 1, 0), (1, 1, 1)),
        SlipFamily("{112}<111>", (1, 1, 2), (1, 1, 1)),
    ),
    "hcp": (
        SlipFamily("{0001}<11-20>", (0, 0, 0, 1), (2, -1, -1, 0), enumerator="hex"),
        SlipFamily("{10-10}<11-20>", (1, 0, -1, 0), (2, -1, -1, 0), enumerator="hex"),
        SlipFamily("{10-11}<11-20>", (1, 0, -1, 1), (2, -1, -1, 0), enumerator="hex"),
        SlipFamily("{10-11}<11-23>", (1, 0, -1, 1), (2, -1, -1, -3), enumerator="hex"),
        SlipFamily("{11-22}<11-23>", (1, 1, -2, 2), (2, -1, -1, -3), enumerator="hex"),
    ),
}

# Explicit ORDERED FCC {111}<110> slip table — the hand-authored v2.x sequence
# (forward_model._SLIP_SYSTEM_111, deleted in M4 Stage 4.3a Task 8). The
# symmetry enumerator (`_enumerate_family`) sorts planes/Burgers
# lexicographically, which does NOT match this order. The ORDER is load-bearing:
# `random_dislocations` draws `rng.integers(0, 12)` into this list, so the
# sequence determines which (b, n, t) each dislocation gets, and the wall mode
# uses entry [0] as its single slip system. Returning the symmetry enumeration
# instead would silently change every FCC random/wall forward image. The set
# (b, n, t up to sign) is identical to the enumerator output — asserted in
# tests (`test_fcc_ordered_table_is_complete_111_110_family`,
# `test_fcc_registry_equals_legacy_slip_table`) and guarded at module import
# below — so nothing is dropped; only the order is pinned for bit-identity.
_FCC_111_110_ORDERED: tuple[
    tuple[tuple[int, int, int], tuple[int, int, int], tuple[int, int, int]], ...
] = (
    # Plane (1, 1, 1)
    ((1, -1, 0), (1, 1, 1), (1, 1, -2)),
    ((-1, 0, 1), (1, 1, 1), (-1, 2, -1)),
    ((0, 1, -1), (1, 1, 1), (-2, 1, 1)),
    # Plane (1, -1, 1)
    ((1, 1, 0), (1, -1, 1), (1, -1, -2)),
    ((-1, 0, 1), (1, -1, 1), (-1, -2, -1)),
    ((0, -1, -1), (1, -1, 1), (-2, -1, 1)),
    # Plane (-1, 1, 1)
    ((0, 1, -1), (-1, 1, 1), (-2, -1, -1)),
    ((1, 0, 1), (-1, 1, 1), (1, 2, -1)),
    ((1, 1, 0), (-1, 1, 1), (-1, 1, -2)),
    # Plane (1, 1, -1)
    ((0, 1, 1), (1, 1, -1), (2, -1, 1)),
    ((1, -1, 0), (1, 1, -1), (-1, -1, -2)),
    ((1, 0, 1), (1, 1, -1), (1, -2, -1)),
)


def _variants(rep: tuple[int, int, int]) -> set[tuple[int, int, int]]:
    """All distinct sign+permutation variants of a Miller family rep."""
    out: set[tuple[int, int, int]] = set()
    for perm in set(itertools.permutations(rep)):
        for signs in itertools.product((1, -1), repeat=3):
            out.add(
                cast("tuple[int, int, int]", tuple(s * c for s, c in zip(signs, perm, strict=True)))
            )
    return out


def _canon(v: tuple[int, int, int]) -> tuple[int, int, int]:
    """Canonical sign: leading nonzero positive (so v and -v collapse)."""
    for c in v:
        if c != 0:
            return v if c > 0 else tuple(-x for x in v)  # type: ignore[return-value]
    return v


def _enumerate_orbit(fam: SlipFamily) -> list[SlipSystem]:
    """Symmetry-orbit enumeration: lexicographic plane/Burgers expansion.

    The generic glide-system generator. Order is the deterministic
    ``sorted(planes) x sorted(burgers)`` sequence — fine for BCC (no legacy to
    match) but NOT the v2.x FCC order, which `_enumerate_family` overrides for
    bit-identity.
    """
    planes = {_canon(p) for p in _variants(cast("tuple[int, int, int]", fam.plane_family))}
    burgers = _variants(cast("tuple[int, int, int]", fam.burgers_family))
    seen: set[tuple[tuple[int, int, int], tuple[int, int, int]]] = set()
    systems: list[SlipSystem] = []
    for n in sorted(planes):
        for b in sorted(burgers):
            if b[0] * n[0] + b[1] * n[1] + b[2] * n[2] != 0:
                continue  # not a glide system
            key = (_canon(b), n)
            if key in seen:
                continue
            seen.add(key)
            t = cast("tuple[int, int, int]", tuple(int(x) for x in np.cross(n, b)))
            systems.append(SlipSystem(b=b, n=n, t=t, family=fam.name))
    return systems


def _variants_hex_4(rep4: tuple[int, int, int, int]) -> set[tuple[int, int, int, int]]:
    """Hexagonal-point-group orbit of a 4-index rep, in 4-index.

    In Miller–Bravais notation the 6/mmm operations act as:
      * all permutations of the first three indices (the (h,k,i)/(u,v,t) triple),
      * an independent sign flip of the 4th index (l/w) — the σ_h mirror,
      * an overall sign flip — inversion.
    |S3| · 2 · 2 = 24 = |6/mmm|.  (Permuting the triple keeps t = -(u+v) valid.)
    Permuting a valid triple always yields another valid triple — the constraint c = -(a+b) is preserved because the three elements always sum to zero.
    """
    a, b, c, d = rep4
    out: set[tuple[int, int, int, int]] = set()
    for perm in set(itertools.permutations((a, b, c))):
        for ld in (d, -d):
            for sign in (1, -1):
                out.add((sign * perm[0], sign * perm[1], sign * perm[2], sign * ld))
    return out


def _enumerate_hex(fam: SlipFamily) -> list[SlipSystem]:
    """Glide-system enumeration for an HCP family (4-index reps in plane_family/burgers_family).

    Generates the hexagonal orbit of the plane and Burgers reps (4-index),
    converts each to reduced 3-index, pairs plane × Burgers, keeps b·n==0
    (metric-free glide), dedups ±(b, n).  ``t`` is the integer cross n×b — a
    deterministic placeholder; the PHYSICAL line direction is recomputed in
    Cartesian by the Ud builder for the non-cubic frame, so this integer t is
    never used for HCP geometry (only for provenance symmetry with the cubic
    SlipSystem layout).
    """
    plane4 = cast("tuple[int, int, int, int]", fam.plane_family)
    burg4 = cast("tuple[int, int, int, int]", fam.burgers_family)
    planes = sorted({_canon(hkil_to_hkl(p)) for p in _variants_hex_4(plane4)})
    burgers = sorted({uvtw_to_uvw(bb) for bb in _variants_hex_4(burg4)})
    seen: set[tuple[tuple[int, int, int], tuple[int, int, int]]] = set()
    systems: list[SlipSystem] = []
    for n in planes:
        for b in burgers:
            if b[0] * n[0] + b[1] * n[1] + b[2] * n[2] != 0:
                continue
            key = (_canon(b), n)
            if key in seen:
                continue
            seen.add(key)
            t = cast("tuple[int, int, int]", tuple(int(x) for x in np.cross(n, b)))
            systems.append(SlipSystem(b=b, n=n, t=t, family=fam.name))
    return systems


def _enumerate_family(fam: SlipFamily) -> list[SlipSystem]:
    if fam.enumerator == "hex":
        return _enumerate_hex(fam)
    if fam.literal:
        # Literal families: yield exactly one system from the stored (b, n) pair,
        # with no symmetry-orbit expansion. The b.n==0 check was done at registration.
        n = cast("tuple[int, int, int]", fam.plane_family)
        b = cast("tuple[int, int, int]", fam.burgers_family)
        t = cast("tuple[int, int, int]", tuple(int(x) for x in np.cross(n, b)))
        return [SlipSystem(b=b, n=n, t=t, family=fam.name)]
    # Match the canonical {111}<110> rep (name + plane + burgers) so a custom
    # family reusing the name can't accidentally hit the ordered FCC table.
    if (
        fam.name == "{111}<110>"
        and fam.plane_family == (1, 1, 1)
        and fam.burgers_family == (1, 1, 0)
    ):
        # FCC {111}<110>: return the explicit ORDERED table, not the lexicographic
        # symmetry enumeration, so the v2.x random/wall draw order is preserved
        # bit-for-bit (see _FCC_111_110_ORDERED). Set-completeness vs the
        # enumerator is guarded at import (the assertion below this function).
        return [SlipSystem(b=b, n=n, t=t, family=fam.name) for b, n, t in _FCC_111_110_ORDERED]
    return _enumerate_orbit(fam)


def _assert_fcc_ordered_table_complete() -> None:
    """Guard (run at import): the explicit ordered FCC table must SET-equal the
    full {111}<110> symmetry orbit, so pinning the order never drops a system."""
    orbit = _enumerate_orbit(SlipFamily("{111}<110>", (1, 1, 1), (1, 1, 0)))
    orbit_set = {(_canon(s.b), _canon(s.n)) for s in orbit}
    table_set = {(_canon(b), _canon(n)) for b, n, _t in _FCC_111_110_ORDERED}
    if orbit_set != table_set or len(_FCC_111_110_ORDERED) != len(orbit):
        raise AssertionError(  # pragma: no cover - defensive import-time guard
            "_FCC_111_110_ORDERED desynced from the {111}<110> symmetry orbit: "
            f"table has {len(_FCC_111_110_ORDERED)} systems {sorted(table_set)}, "
            f"orbit has {len(orbit)} {sorted(orbit_set)}."
        )


_assert_fcc_ordered_table_complete()


def _assert_hcp_family_counts() -> None:
    """Guard (run at import): the hexagonal enumerator yields the textbook counts."""
    expected = {
        "{0001}<11-20>": 3,
        "{10-10}<11-20>": 3,
        "{10-11}<11-20>": 6,
        "{10-11}<11-23>": 12,
        "{11-22}<11-23>": 6,
    }
    for fam in _REGISTRY["hcp"]:
        got = len(_enumerate_family(fam))
        if got != expected[fam.name]:
            raise AssertionError(  # pragma: no cover - defensive import-time guard
                f"HCP family {fam.name}: enumerator produced {got} systems, expected {expected[fam.name]}."
            )


_assert_hcp_family_counts()


def _families_for(structure: str, families: list[str] | None) -> tuple[SlipFamily, ...]:
    if structure not in _REGISTRY:
        raise ValueError(f"unknown structure {structure!r}; expected one of {sorted(_REGISTRY)}")
    avail = _REGISTRY[structure]
    if families is None:
        return avail
    by_name = {f.name: f for f in avail}
    try:
        return tuple(by_name[name] for name in families)
    except KeyError as exc:
        raise ValueError(
            f"slip family {exc.args[0]!r} not defined for {structure!r}; "
            f"available: {sorted(by_name)}"
        ) from None


def slip_systems(structure: str, *, families: list[str] | None = None) -> list[SlipSystem]:
    """All (b, n, t) slip systems for a structure (optionally a family subset)."""
    out: list[SlipSystem] = []
    for fam in _families_for(structure, families):
        out.extend(_enumerate_family(fam))
    return out


def plane_normals(
    structure: str, *, families: list[str] | None = None
) -> list[tuple[int, int, int]]:
    """Distinct slip-plane normals (replaces _ALL_111_PLANES), canonical sign."""
    seen: list[tuple[int, int, int]] = []
    for s in slip_systems(structure, families=families):
        c = _canon(s.n)
        if c not in seen:
            seen.append(c)
    return seen


# Lattice-translation fraction per family: the slip Burgers is this fraction
# of the integer direction's lattice vector (1/2 for the centered-lattice
# translations <110>_fcc, <111>_bcc).
_BURGERS_FRACTION: dict[str, float] = {
    "{111}<110>": 0.5,
    "{110}<111>": 0.5,
    "{112}<111>": 0.5,
}


def burgers_in_plane(
    structure: str, plane: tuple[int, int, int], *, families: list[str] | None = None
) -> np.ndarray:
    """Unit Burgers directions lying in `plane` (+ negatives), shape (m, 3).

    Replaces crystal.burgers._BASIS_TABLE/burgers_vectors. Per-vector
    Euclidean normalization (bit-identical to the old /sqrt(2) for FCC <110>).
    """
    cn = _canon(plane)
    pos: list[tuple[int, int, int]] = []
    for s in slip_systems(structure, families=families):
        if _canon(s.n) == cn and _canon(s.b) not in pos:
            pos.append(_canon(s.b))
    if not pos:
        raise ValueError(
            f"{plane} is not a slip plane for structure {structure!r}; "
            f"planes: {plane_normals(structure, families=families)}"
        )
    basis = np.array(pos, dtype=float)
    unit = basis / np.linalg.norm(basis, axis=1, keepdims=True)
    return np.vstack([unit, -unit])


def burgers_in_plane_int(
    structure: str, plane: tuple[int, int, int], *, families: list[str] | None = None
) -> np.ndarray:
    """Integer (u, v, w) Burgers directions lying in `plane` (+ negatives), shape (m, 3).

    The INTEGER-Miller companion of ``burgers_in_plane``: row i here is the
    integer direction whose unit-normalization is row i of ``burgers_in_plane``
    (same plane, same families) — i.e. the index ``b_idx`` aligns across the two.
    Use this for the integer Burgers LABEL written to HDF5 in the non-FCC identify
    branch (the FCC path keeps its own ``*√2`` reconstruction for bit-identity;
    that assumption is ⟨110⟩-specific and wrong for BCC ⟨111⟩, so general
    structures read the integer Burgers from the registry instead).
    """
    cn = _canon(plane)
    pos: list[tuple[int, int, int]] = []
    for s in slip_systems(structure, families=families):
        if _canon(s.n) == cn and _canon(s.b) not in pos:
            pos.append(_canon(s.b))
    if not pos:
        raise ValueError(
            f"{plane} is not a slip plane for structure {structure!r}; "
            f"planes: {plane_normals(structure, families=families)}"
        )
    basis = np.array(pos, dtype=int)
    return np.vstack([basis, -basis])


def derive_structure_type(
    *,
    structure_type: str | None,
    space_group: str | None,
    lattice: str | None,
) -> str:
    """Resolve the structure family.

    Precedence: when a space group is present it is authoritative (the
    crystallographic evidence overrides a possibly-wrong user assertion) —
    derive from it and raise if an explicit structure_type contradicts it.
    With no space group, explicit structure_type wins over the default; with
    neither, 'fcc' (back-compat). The `lattice` param is accepted for API
    stability (4.3b will use it for HCP cell conversion) and is currently unused.
    """
    if space_group is not None:
        from dfxm_geo.crystal.cif import space_group_structure_family

        derived = space_group_structure_family(space_group)
        if structure_type is not None and structure_type != derived:
            raise ValueError(
                f"structure_type={structure_type!r} contradicts space group "
                f"{space_group!r} (implies {derived!r})."
            )
        return derived
    if structure_type is not None:
        if structure_type not in _REGISTRY:
            raise ValueError(
                f"unknown structure_type {structure_type!r}; expected one of {sorted(_REGISTRY)}."
            )
        return structure_type
    return "fcc"


def register_custom(name: str, systems: list[dict]) -> None:
    """Register a user-defined structure from ``[[crystal.slip_system]]`` entries.

    Each entry: ``{"plane": (h, k, l), "burgers": (u, v, w)}``. Validates
    b·n == 0. Stored as literal single-system families so
    ``slip_systems(name)`` returns exactly those systems (no symmetry-orbit
    expansion).

    Args:
        name: structure key (e.g. ``"custom:Fe"``); replaces any existing entry.
        systems: list of dicts with "plane" and "burgers" keys (integer triples).

    Raises:
        ValueError: if any system has b·n != 0 (not a glide system).
    """
    fams: list[SlipFamily] = []
    for i, s in enumerate(systems):
        plane = tuple(int(x) for x in s["plane"])
        b = tuple(int(x) for x in s["burgers"])
        if b[0] * plane[0] + b[1] * plane[1] + b[2] * plane[2] != 0:
            raise ValueError(f"custom slip system {i}: b.n != 0 (b={b}, n={plane}); not glide")
        fams.append(
            SlipFamily(
                f"custom{i}",
                cast("tuple[int, int, int]", plane),
                cast("tuple[int, int, int]", b),
                literal=True,
            )
        )
    new = tuple(fams)
    if name in _REGISTRY and _REGISTRY[name] != new:
        import warnings

        warnings.warn(
            f"register_custom: replacing existing registry entry {name!r} with "
            "different slip systems; if two configs share the same 'material' key "
            "this may be unintentional.",
            stacklevel=2,
        )
    _REGISTRY[name] = new


def burgers_magnitude(structure: str, family: str, cell: UnitCell) -> float:
    """Burgers magnitude |b| in micrometres for a structure's family, from the cell.

    |b| = fraction * |A . b_int|, A in metres -> result in um. Cubic FCC
    1/2<110> -> a/sqrt(2); BCC 1/2<111> -> a*sqrt(3)/2.

    Fraction selection:
    - LITERAL families (``fam.literal``: the user-supplied ``[[crystal.slip_system]]``
      escape hatch, registered via ``register_custom``) carry the ACTUAL integer
      Burgers vector, so fraction = 1.0 (no centered-lattice ½ halving) —
      |b| = |A·b_int|·1e6.
    - NON-literal (enumerated FCC/BCC) families MUST be in ``_BURGERS_FRACTION``;
      a forgotten KNOWN family is a loud error (Task-2 hardening preserved).
    """
    if structure not in _REGISTRY:
        raise ValueError(f"unknown structure {structure!r}; expected one of {sorted(_REGISTRY)}")
    matches = [f for f in _REGISTRY[structure] if f.name == family]
    if not matches:
        raise ValueError(
            f"slip family {family!r} not defined for {structure!r}; "
            f"available: {sorted(f.name for f in _REGISTRY[structure])}"
        )
    fam = matches[0]
    if fam.literal:
        # User supplied the actual integer Burgers vector via the custom hatch:
        # no centered-lattice ½ halving — the magnitude is |A·b_int| directly.
        frac = 1.0
    else:
        if family not in _BURGERS_FRACTION:
            raise ValueError(
                f"no lattice-translation fraction registered for family {family!r}; "
                f"add it to _BURGERS_FRACTION."
            )
        frac = _BURGERS_FRACTION[family]
    b_int = np.array(fam.burgers_family, dtype=float)
    cart = cell.A @ b_int  # metres
    return float(frac * np.linalg.norm(cart) * 1e6)
