"""Data-driven slip-system registry for FCC / BCC (+ user-defined).

A slip system is (b, n, t): Burgers direction b in the glide plane with
normal n, and line direction t = n x b. Tables are generated by enumerating
the sign/permutation variants of a representative plane and Burgers family
under the cubic point group, filtering to b.n == 0 (glide), deduplicating
+/-(b, n) pairs.

CUBIC ONLY in 4.3a: Miller indices are treated as Cartesian (valid for
cubic — FCC and BCC). HCP (4.3b) converts via the cell matrix first.
Spec: docs/superpowers/specs/2026-06-13-m4-stage43-slip-systems-design.md.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass
from typing import TYPE_CHECKING, cast

import numpy as np

if TYPE_CHECKING:
    from dfxm_geo.crystal.cell import UnitCell


@dataclass(frozen=True)
class SlipFamily:
    name: str
    plane_family: tuple[int, int, int]
    burgers_family: tuple[int, int, int]


@dataclass(frozen=True)
class SlipSystem:
    b: tuple[int, int, int]  # integer Burgers direction (Miller)
    n: tuple[int, int, int]  # integer plane normal (Miller)
    t: tuple[int, int, int]  # integer line direction n x b
    family: str


_REGISTRY: dict[str, tuple[SlipFamily, ...]] = {
    "fcc": (SlipFamily("{111}<110>", (1, 1, 1), (1, 1, 0)),),
    "bcc": (
        SlipFamily("{110}<111>", (1, 1, 0), (1, 1, 1)),
        SlipFamily("{112}<111>", (1, 1, 2), (1, 1, 1)),
    ),
}


def _variants(rep: tuple[int, int, int]) -> set[tuple[int, int, int]]:
    """All distinct sign+permutation variants of a Miller family rep."""
    out: set[tuple[int, int, int]] = set()
    for perm in set(itertools.permutations(rep)):
        for signs in itertools.product((1, -1), repeat=3):
            out.add(
                cast("tuple[int, int, int]", tuple(s * c for s, c in zip(signs, perm, strict=True)))
            )
    return out


def _canon(v: tuple[int, int, int]) -> tuple[int, int, int]:
    """Canonical sign: leading nonzero positive (so v and -v collapse)."""
    for c in v:
        if c != 0:
            return v if c > 0 else tuple(-x for x in v)  # type: ignore[return-value]
    return v


def _enumerate_family(fam: SlipFamily) -> list[SlipSystem]:
    planes = {_canon(p) for p in _variants(fam.plane_family)}
    burgers = _variants(fam.burgers_family)
    seen: set[tuple[tuple[int, int, int], tuple[int, int, int]]] = set()
    systems: list[SlipSystem] = []
    for n in sorted(planes):
        for b in sorted(burgers):
            if b[0] * n[0] + b[1] * n[1] + b[2] * n[2] != 0:
                continue  # not a glide system
            key = (_canon(b), n)
            if key in seen:
                continue
            seen.add(key)
            t = cast("tuple[int, int, int]", tuple(int(x) for x in np.cross(n, b)))
            systems.append(SlipSystem(b=b, n=n, t=t, family=fam.name))
    return systems


def _families_for(structure: str, families: list[str] | None) -> tuple[SlipFamily, ...]:
    if structure not in _REGISTRY:
        raise ValueError(f"unknown structure {structure!r}; expected one of {sorted(_REGISTRY)}")
    avail = _REGISTRY[structure]
    if families is None:
        return avail
    by_name = {f.name: f for f in avail}
    try:
        return tuple(by_name[name] for name in families)
    except KeyError as exc:
        raise ValueError(
            f"slip family {exc.args[0]!r} not defined for {structure!r}; "
            f"available: {sorted(by_name)}"
        ) from None


def slip_systems(structure: str, *, families: list[str] | None = None) -> list[SlipSystem]:
    """All (b, n, t) slip systems for a structure (optionally a family subset)."""
    out: list[SlipSystem] = []
    for fam in _families_for(structure, families):
        out.extend(_enumerate_family(fam))
    return out


def plane_normals(
    structure: str, *, families: list[str] | None = None
) -> list[tuple[int, int, int]]:
    """Distinct slip-plane normals (replaces _ALL_111_PLANES), canonical sign."""
    seen: list[tuple[int, int, int]] = []
    for s in slip_systems(structure, families=families):
        c = _canon(s.n)
        if c not in seen:
            seen.append(c)
    return seen


# Lattice-translation fraction per family: the slip Burgers is this fraction
# of the integer direction's lattice vector (1/2 for the centered-lattice
# translations <110>_fcc, <111>_bcc).
_BURGERS_FRACTION: dict[str, float] = {
    "{111}<110>": 0.5,
    "{110}<111>": 0.5,
    "{112}<111>": 0.5,
}


def burgers_in_plane(
    structure: str, plane: tuple[int, int, int], *, families: list[str] | None = None
) -> np.ndarray:
    """Unit Burgers directions lying in `plane` (+ negatives), shape (m, 3).

    Replaces crystal.burgers._BASIS_TABLE/burgers_vectors. Per-vector
    Euclidean normalization (bit-identical to the old /sqrt(2) for FCC <110>).
    """
    cn = _canon(plane)
    pos: list[tuple[int, int, int]] = []
    for s in slip_systems(structure, families=families):
        if _canon(s.n) == cn and _canon(s.b) not in pos:
            pos.append(_canon(s.b))
    if not pos:
        raise ValueError(
            f"{plane} is not a slip plane for structure {structure!r}; "
            f"planes: {plane_normals(structure, families=families)}"
        )
    basis = np.array(pos, dtype=float)
    unit = basis / np.linalg.norm(basis, axis=1, keepdims=True)
    return np.vstack([unit, -unit])


def derive_structure_type(
    *,
    structure_type: str | None,
    space_group: str | None,
    lattice: str | None,
) -> str:
    """Resolve the structure family.

    Precedence: when a space group is present it is authoritative (the
    crystallographic evidence overrides a possibly-wrong user assertion) —
    derive from it and raise if an explicit structure_type contradicts it.
    With no space group, explicit structure_type wins over the default; with
    neither, 'fcc' (back-compat). The `lattice` param is accepted for API
    stability (4.3b will use it for HCP cell conversion) and is currently unused.
    """
    if space_group is not None:
        from dfxm_geo.crystal.cif import space_group_structure_family

        derived = space_group_structure_family(space_group)
        if structure_type is not None and structure_type != derived:
            raise ValueError(
                f"structure_type={structure_type!r} contradicts space group "
                f"{space_group!r} (implies {derived!r})."
            )
        return derived
    if structure_type is not None:
        if structure_type not in _REGISTRY and structure_type != "hcp":
            raise ValueError(
                f"unknown structure_type {structure_type!r}; expected one of "
                f"{sorted(_REGISTRY)} (hcp lands in 4.3b)."
            )
        return structure_type
    return "fcc"


def burgers_magnitude(structure: str, family: str, cell: UnitCell) -> float:
    """Burgers magnitude |b| in micrometres for a structure's family, from the cell.

    |b| = fraction * |A . b_int|, A in metres -> result in um. Cubic FCC
    1/2<110> -> a/sqrt(2); BCC 1/2<111> -> a*sqrt(3)/2.
    """
    if structure not in _REGISTRY:
        raise ValueError(f"unknown structure {structure!r}; expected one of {sorted(_REGISTRY)}")
    matches = [f for f in _REGISTRY[structure] if f.name == family]
    if not matches:
        raise ValueError(
            f"slip family {family!r} not defined for {structure!r}; "
            f"available: {sorted(f.name for f in _REGISTRY[structure])}"
        )
    if family not in _BURGERS_FRACTION:
        raise ValueError(
            f"no lattice-translation fraction registered for family {family!r}; "
            f"add it to _BURGERS_FRACTION."
        )
    b_int = np.array(matches[0].burgers_family, dtype=float)
    cart = cell.A @ b_int  # metres
    return float(_BURGERS_FRACTION[family] * np.linalg.norm(cart) * 1e6)
